
// Auto-generated by AutoPilot on 28-07-2023 at 13:10:40

const express = require('express');
const router = express.Router();

// Define the route for the API
router.get('/biryani', (req, res) => {
  // Create an array of steps to cook biryani
  const steps = [
    'Wash and soak the rice for 30 minutes.',
    'Prepare the marinade for the meat and set aside for at least 30 minutes.',
    'Heat oil in a large pot and add whole spices.',
    'Add the marinated meat and fry for a few minutes.',
    'Add the rice and fry for a few minutes.',
    'Add water, salt, and other spices and bring to a boil.',
    'Reduce the heat to a low, cover and cook for 20 minutes.',
    'Turn off the heat and let the biryani sit for 10 minutes before serving.'
  ];

  // Return the array of steps
  res.status(200).json({ steps });
});

module.exports = router;